### PR TITLE
Specify required-features for examples/tests which require non-defaul…

### PR DESCRIPTION
**Pull request by ignatenkobrain**
…t features

Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@Mcat12 it would be so much nicer if you would actually understand issue instead of simply closing issue saying "you are doing it wrong"…

**Comment by Mcat12** [comment]
I did understand the issue. I tested it myself, on Fedora. The test and example documentation was there. You opened an issue somehow relating incorrect usage of the project configuration with Fedora, without reading the readme to understand what might be going wrong. I explained the cause of your issue and pointed you to the resolution.

I'm thankful for you opening this PR, but please do some research before blaming others. Yes, you were "doing it wrong". Yes, it would be better if these config changes are made.

**Comment by ignatenkobrain** [comment]
> I'm thankful for you opening this PR, but please do some research before blaming others. Yes, you were "doing it wrong". Yes, it would be better if these config changes are made.

I did not blame anybody, I just said that it is unfair to close the issue with words "you are doing it wrong", given that we run `cargo test` on at least thousand of other crates and 99% of them work without any problems. And they have similar cases, which are solved by using required-features. So you could have just said "you are welcome to open PR which adds usage of required-features".

**Comment by ignatenkobrain** [comment]
> I did not blame anybody

At least I did not intend to do so.

**Comment by Mcat12** [comment]
I would rather not get into an argument, it's unproductive. The point is, you did not do the bare minimum of reading the readme before creating an issue. Isn't it "unfair" to open issues that could be solved by just doing the bare minimum of reading the readme?

Not everyone knows all of the configuration options of cargo, so I'm glad to see that this test issue has a solution with "required-features".

**Comment by pyros2097** [comment]
Yep no arguments please. Be sensitive and nice to one another.

@Mcat12 it would have been nice if you had left the issue open for a little longer or until he replied so that others could also help out if needed.

@ignatenkobrain  you should have read the readme completely but its ok these things do happen. 
We need to setup and issue template to help in resolving these kind of issues in the future. 

Misunderstandings do happen. Its best we assume good about one another and be good no matter what. 😺 .People do have bad days.

**Comment by pyros2097** [comment]
Also @ignatenkobrain thanks for the PR if it helps newbies to cargo or some else it will be useful.

**Pull request merged**
