### PR TITLE
Add warp example

### PR DESCRIPTION
**Pull request by D4nte**
Does what it says on the tin.

### CODE REVIEW

**Comment by pyros2097** [comment]
LGTM. Thanks @D4nte

**Comment by pyros2097** [comment]
Oops forgot check is not passing @D4nte can you fix the tests

**Comment by D4nte** [comment]
@pyros2097 can you point me to the failed check? All tests that are run by travis look good locally.

**Comment by pyros2097** [comment]
Huh... Funny it shows passed in the Travis CI dashboard. I guess it's a false positive. A bug in the webhook maybe,

**Pull request merged**
