### PR TITLE
Add iter() method to list files

### LINKED ISSUE #29: Method for getting a list of the available files
It would be nice to have a method such as `fn list(&self) -> Vec<Path>` or `fn list(&self) -> Vec<String>` to get a list of the available files. My use case is that I want to have a few specifications for different models of TVs, and rather than typing out the names of the models twice, I would just name the file describing the TV after the appropriate display option, and then retrieve that list in the program.

### PR DESCRIPTION
**Pull request by vemoo**
Fixes #29.

I first tried by putting the code that lists the files in the code generated in debug, but that introduces a dependecy on walkdir and fails if the user doesn't have it.

Then I tried to create a `pub fn get_files` and the using it inside the debug code, but that fails because a proc_macro crate cannot have more than one `pub fn`.

FInally I managed to make it work by spliting the crate in two:
- rust_embed_impl: has the macro implementation, is not public
- rust_embed: reexports the macro from rust_embed_impl and has the get_files function. 

I have updated the readme but maybe some more examples are needed, but i wanted to get some feedback before continuing.

### CODE REVIEW

**Comment by pyros2097** [comment]
Nice work vemoo. Could you also bump up the minor version and update it in the readme.
The code looks great.

**Comment by vemoo** [comment]
I added this commit https://github.com/pyros2097/rust-embed/pull/45/commits/f7cc15722d0b9d93cfe3ff4481a46f4823ce7e75 because I thought there was an issue when resolving the folder in nested files. But I now realise it was the same as issue #30 and what fixed it was using `Path::join`, and my change introduced other change that may not be desired.

It's not explicitly documented but the current behaviour to resolve the folder is:

- On debug and when "debug-embed" is not enabled: resolved at runtime relative to where the binary was run from
- On release or when "debug-embed" is enabled: resolved at compile time relative to where cargo is invoked from

That commit chages that so that the folder is always resolved at compile time.
Should I remove that commit entirely and fix #30 separately, or fix it so that it works as before?

In any case I will mention that logic in the readme.

**Comment by pyros2097** [comment]
Noice Work. LGTM!

**Comment by vemoo** [comment]
@pyros2097 I think you missed my previous comment. This line https://github.com/pyros2097/rust-embed/blob/eba4b59edcfe61f2489facd306cb8750aeea7f5c/impl/src/lib.rs#L20 should probably be removed so that the code and the readme are consistent.

**Comment by pyros2097** [comment]
Ohhh.. I missed the question. You can remove that commit and fix #30 separately so as to track it properly. I haven't yet published so go ahead and make those changes.

**Comment by vemoo** [comment]
I've created #46 to address it.

**Pull request merged**
