### PR TITLE
Compile on stable Rust versions

### LINKED ISSUE #18: Make it work on Stable Rust
It seems many useful libraries like serde, diesel are working in stable rust right now. We should also move this to use stable rust so that it could be more in tune to work in production environments.

Here is the list of changes I can think of,
- [ ]  Remove `#![feature(attr_literals)]`

### PR DESCRIPTION
**Pull request by Mcat12**
Changed the derive attribute style so we don't need `attr_literals`:
```rust
#[folder("assets/")]
```
to
```rust
#[folder = "assets/"]
```

Also included:
- Added stable Rust to the CI
- Fixed the CI cache (runs much faster now)
- Allowed nightly to fail
- Moved the rocket dependencies behind a feature flag so that the tests could run on stable

Fixes #18

### CODE REVIEW

**Comment by pyros2097** [comment]
@Mcat12 Thanks a lot. Was planning to do the same thing. Will push out a new release tomorrow.

**Comment by pyros2097** [comment]
Removing the --tests from CI prevents cargo from running any tests at all.
This is in the ci's runner logs
```
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by Mcat12** [comment]
Hmm, adding the `--tests` compiles the examples, which fails because the rocket one requires rocket.

I'll look into this tonight.

**Comment by Mcat12** [comment]
According to this comment, starting with 1.27 `cargo test --tests --lib` will run only unit and integration tests (not examples). However, for now it also does examples.
https://github.com/rust-lang/cargo/issues/5387#issuecomment-388937131

For now though, we can manually specify the test to run:
```
cargo test --test lib
```

**Comment by pyros2097** [comment]
Yes this is what I did also.

**Pull request merged**
